### ISSUE TITLE
Map overflow and erratic tiles

### ISSUE THREAD

**Issue by amaillere** [atomfrede/generator-jhipster-leaflet#3]
Do you have any idea what can cause that ?
![generator-jhipster-leaflet](https://cloud.githubusercontent.com/assets/2863591/14257163/b87a8b0e-fa9c-11e5-9f88-b606e0a9d6aa.PNG)

I generated on a clean new jhispter 3 application.

**Comment by atomfrede** [comment]
Do you have javascript errors?

**Comment by amaillere** [comment]
absoluytely no error, that's the strange thing...
broken translations happen  when I reload on this page, when i start from homepage, labels are OK (classic jhipster behaviour ,dependencies are not set in the view)

I see you're building the application again :)
let me know if you need more information
problem happens on Chrome, FF and Edge.

**Comment by atomfrede** [comment]
I've just checked with latest jhipster master and it renders correctly. Can you provide your ``yo.rc`` file with the complete config?

**Comment by amaillere** [comment]
here it is :
`{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "tmptest",
    "packageName": "fr.adn.annuaire",
    "packageFolder": "fr/adn/annuaire",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "26283afac4239ce3dbf5aca909e21a44b4bbd640",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}`

**Comment by amaillere** [comment]
Got it,for some reason, the CSS dependency has not been added to bower.json!
That probably from my install
I close the issue and will make another one if needed
Sorry to have bother you and thank you for your time!

**Comment by atomfrede** [comment]
:+1: Great to hear it works. Yes sometimes bower works not that reliable.
