### ISSUE TITLE
I'm not getting the result

### ISSUE THREAD

**Issue by AppreciateIT** [atomfrede/generator-jhipster-leaflet#4]
I'm running the generator after creating a JHipster monolithic app.  It looks like it works and I see the new files in the source.  I'm creating a docker image so I do ./mvnw package -Pprod dockerfile:build
I run the container with docker-compose -f src/main/docker/app.yml up -d
The containers run, I've got three containers: a jhipster registry, a postgres database, and the monolith app.  I log in as admin, and it's just the regular "Welcome JHipster" screen.  There is no link to the leaflet page in the menu.  Just the normal menu with Home, Entities, Account, Administration, & Language.  Am I doing something wrong or missing a step?  Any clues?

Cheers,

Matt

**Comment by atomfrede** [comment]
Hi Matt, sounds like you are using angular 4+. This module does only work with angular 1 at the moment.

**Comment by AppreciateIT** [comment]
Oh, I think the monolith was set for Angular JS 1.5.8.  No good?

**Comment by AppreciateIT** [comment]
Doh, I just realized it does work if I manually switch to the route http://localhost:8080/#/leaflet-maps
Sorry, false alarm.  Thanks for being around to ask questions though.  Keep up the good fight.  
Cheers,
Matt
